spring.application.name=JobApplication
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/job_application_db
spring.datasource.username=products_application
spring.datasource.password=password12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=MiClaveSecretaSuperSeguraParaJWTde256Bits!!
jwt.expiration-ms=86400000

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.name=Bolsa de Empleo